Allow disabling !forceready via get5_allow_force_ready.
splewis/get5 pull request #882
Opened 2022-09-17 16:51 UTC by nickdnk

I was looking at the forks people have made of get5 to figure out which low-hanging fruits people felt were missing, and one of them had simply removed access to the `!forceready` command, so I've added this as an option.

I also noticed that the message informing players that they can `!forceready` is misleading with regards to the "if you have less than X players" part, as it's only accessible if you have at least `min_players_to_ready` **and** it is also accessible if your team is full and someone just didn't ready, so I removed that part of the message using my Google-translate skills.

@Saph1s Please check the Russian
@SidiBecker Please check the Portugese
@enerbewow Please check the Hungarian.

2022-09-17 16:52 UTC, nickdnk commented on translations/chi/get5.phrases.txt
> +        "chi"            "您可以输入{1}来强制准备您的队伍。"
According to Google, this variable was in the wrong place, so I've best-efforted it to be correct.

2022-09-17 18:04 UTC, Saph1s requested changes

2022-09-20 06:33 UTC, enerbewow commented
I'll need some time, cause my free time is stricted nowdays, maybe in this week I can have some free time to check it

2022-09-21 03:12 UTC, nickdnk commented
> I'll need some time, cause my free time is stricted nowdays, maybe in this week I can have some free time to check it

Fair enough, but all you need to do here is:

1. Answer if this is correct, as I removed the last part of the sentence:

    "**Beírhatod a {1} parancsot, ha fel szeretnéd készíteni a csapatod.**"
    
2. Translate this sentence:

    "**The force-ready command is disabled, but can enabled with get5_allow_force_ready.**"
    
 You can just comment here and I'll put it in the code. No actual work required on your part.

2022-09-21 13:35 UTC, enerbewow commented
> > I'll need some time, cause my free time is stricted nowdays, maybe in this week I can have some free time to check it
> 
> Fair enough, but all you need to do here is:
> 
> 1. Answer if this is correct, as I removed the last part of the sentence:
>    "**Beírhatod a {1} parancsot, ha fel szeretnéd készíteni a csapatod.**"
> 2. Translate this sentence:
>    "**The force-ready command is disabled, but can enabled with get5_allow_force_ready.**"
> 
> You can just comment here and I'll put it in the code. No actual work required on your part.

1. **"Beírhatod a {1} parancsot, ha fel szeretnéd készíteni a csapatod."**
Beírhatod - **You can type** , **a** - the , **{command}** , parancsot - **command**, ha - **if**, fel szeretnéd - **you want to**, készíteni - **prepare**, a csapatod - **your team** ---  This is correct✔

ha kevesebb mint {2} játékosod van. --- this means: if you have, less then {2} player.

2. **"The force-ready command is disabled, but can enabled with get5_allow_force_ready."**

HUN Translate:
A !forceready parancs ki van kapcsolva, de engedélyezheted a get5_allow_force_ready paranccsal."
force-ready is not interpret in Hungarian. In raw backtrasnlate is ready with power (by some external force).

2022-09-21 13:44 UTC, nickdnk commented
> "Beírhatod a {1} parancsot, ha fel szeretnéd készíteni a csapatod."
Beírhatod - You can type , a - the , {command} , parancsot - command, ha - if, fel szeretnéd - you want to, készíteni - prepare, a csapatod - your team --- This is correct✔

Great. Thanks.

> HUN Translate: A `!forceready` parancs ki van kapcsolva, de engedélyezheted a get5_allow_force_ready paranccsal." force-ready is not interpret in Hungarian. In raw backtrasnlate is ready with power (by some external force).

You are right, we should inject the variable into the sentence (!forceready) instead of trying to translate it ("the force-ready command"). I will make this change to the English version.

2022-09-21 14:02 UTC, nickdnk commented
@Saph1s 

`Команда для принудительной подготовки отключена, но ее можно включить с помощью {2}.` must have the `!forceready` command injected as the first parameter instead, i.e.: `The !forceready command is disabled, but can be enabled with get5_allow_force_ready.`

2022-09-21 14:03 UTC, SidiBecker requested changes

2022-09-21 14:05 UTC, SidiBecker commented on translations/pt/get5.phrases.txt
>      }
Sorry for the delay,  I forgot to submit my review days ago 🙄

2022-09-21 14:06 UTC, Saph1s requested changes

2022-09-21 14:06 UTC, Saph1s commented on translations/ru/get5.phrases.txt
> +        "ru"            "Команда для принудительной подготовки отключена, но ее можно включить с помощью {2}."
"Команда {1} отключена, но ее можно включить с помощью {2}."

2022-09-21 14:12 UTC, nickdnk commented on translations/pt/get5.phrases.txt
>      }
Hey @SidiBecker. 

Thanks!

See my latest comment. The "!forceready" command must be injected into the `ForceReadyDisabled`-string as the first argument.

2022-09-21 14:18 UTC, SidiBecker requested changes

2022-09-21 14:18 UTC, SidiBecker commented on translations/pt/get5.phrases.txt
>      }
In this case:
```
"ForceReadyDisabled"
    {
        "pt"            "O comando {1} está desativado, mas pode ser ativado com {2}."
    }
```

Translation of  **"The {1} command is disabled, but can be enabled with {2}."**

2022-09-21 14:21 UTC, nickdnk commented
I think we're good now with the translators we have.

2022-09-21 14:51 UTC, merged