Add custom veto logic support
splewis/get5 pull request #962
Opened 2023-01-04 21:21 UTC by nickdnk

This allows the match configuration to come with a `veto_mode` key that takes an array of strings in order to allow a custom veto mode.

Closes https://github.com/splewis/get5/issues/643.

In this example, we do a default "each team bans one, then picks one, last one played":

```json
{
  "num_maps": 3,
  "maplist": [
    "de_dust2",
    "de_mirage",
    "de_inferno",
    "de_ancient",
    "de_vertigo"
  ],
  "veto_mode": [
    "team1_ban",
    "team2_ban",
    "team1_pick",
    "team2_pick"
  ],
  "map_sides": [
    "team2_ct",
    "team1_ct",
    "knife"
  ],
  "team1": {
    "name": "Team A Default",
    "players": {
      "76561197996413459": "PlayerAName1"
    },
    "coaches": {
      "76561197996426735": "CoachAName1"
    }
  },
  "team2": {
    "name": "Team B Default",
    "players": {
      "76561197996413459": "PlayerBName1"
    },
    "coaches": {
      "76561197996426735": "CoachBName1"
    }
  }
}
```

2023-01-16 14:17 UTC, stranden commented
Will #920 be included in this?

2023-01-16 14:19 UTC, nickdnk commented
> Will #920 be included in this?

Maybe. It requires a fair amount of adjustments to translations as "veto" is mentioned in all languages, so it really depends on whether or not we can get people to make this change.

2023-01-17 18:12 UTC, TandelK commented
@nickdnk So with this feature we can configure any place of ban and pick with any Best Of ?

2023-01-17 18:18 UTC, nickdnk commented
> @nickdnk So with this feature we can configure any place of ban and pick with any Best Of ?

Yes, you can create any config that's logically possible.

2023-01-27 21:42 UTC, nickdnk commented
I have tested it and fixed some problems. We now also aim to close #920 with this.

2023-01-28 11:47 UTC, Saph1s requested changes
Russian translation

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "Напишите {1} когда ваша команда будет готова к голосованию."
Напишите {1} когда ваша команда будет готова к выбору карты.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "Карта изменится, как только на GOTV будут показаны вето на карты."
Карта изменится, как только на GOTV будет показан выбор карты.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "{1} готовы для голосования."
{1} готовы для выбора карты.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "{1} вычеркнули {2}."
{1} запретили {2}.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "Капитан пропал по время голосования, голосование приостановлено."
Капитан команды вышел во время выбора карты. Выбор карты приостановлен.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"            "Напишите {1}, когда будете готовы продолжить голосование."
Напишите {1}, когда будете готовы продолжить выбор карты.

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"        "Выберите карту, на которую нужно наложить ВЕТО:"
Выберите карту для запрета:

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"        "Подтвердите, что вы хотите наложить ВЕТО на {1}:"
Подтвердите, что вы хотите запретить {1}:

2023-01-28 11:47 UTC, Saph1s commented on translations/ru/get5.phrases.txt
>          "ru"        "Наложение вето начинается через {1} сек."
Выбор карты начинается через {1}...

2023-01-29 04:22 UTC, nickdnk commented
> Russian translation

Adjusted.

2023-01-29 04:25 UTC, nickdnk commented
@Saph1s I think maybe you should capitalize "BAN" in the confirm translations, as it's capitalized for "PLAY":

```
    "MapVetoPickMenuText"
    {
        "ru"        "Выберите карту для ИГРЫ:"
    }
```

For consistency.

2023-01-29 18:57 UTC, nickdnk commented
I have tested this pretty extensively and also added a bunch of unit tests. Only translations are missing now, or some feedback. I will merge this PR so it can be released as prerelease, and we can update the translations in another PR.

2023-01-29 18:59 UTC, merged

2023-04-07 20:20 UTC, deLuXe83 commented
Hi!
Just tested the new veto/pick system.

It comes out, that esp. when playing workshop maps, the `pick <mapname>` command is very unhandy, because captains sometimes do not know the correct map name (eg. map is called `de_cobblestone `(workshop), but you have to type `de_cbble`).

Would it be possible to get back the old votring system, so you can vote via numbers? (maybe as an option)

Thanks!
Bests!

2023-04-07 20:41 UTC, nickdnk commented
Hello

The old system is not returning. It longer exists. What we can do is add an option to disable formatting the names, so it just prints out "de_cbble" and you can !ban cbble in that case.

Alternatively, we can make it convert know map names to their actual-name equivalent, i.e. `de_cbble` would also match "Cobble" or "Cobblestone".

2023-04-07 22:51 UTC, nickdnk commented
@deLuXe83 https://github.com/splewis/get5/pull/1005/files This should fix your problem, right?

2023-04-07 22:59 UTC, deLuXe83 commented
Hi!
Thx for your reply.
Yeah, cbble might be the most difficult map. As i mentioned I would assume workshop-maps are making the problems.

In our case the system prints out "Cobblestone" but you had to type de_cbble.
Maybe as well case-sensitivity should be turned off?

![WhatsApp Image 2023-04-07 at 21 10 45](https://user-images.githubusercontent.com/37928770/230690048-bf38025b-e2cf-4236-8de0-ce304d032633.jpeg)

2023-04-07 23:22 UTC, deLuXe83 commented
Just came up with another question.

What happens, if following values are set
`"veto_first"	"random"  
"veto_mode"
	{	
	"team1_ban" ""
	"team2_ban" ""
	"team1_ban" ""
	"team2_ban" ""
	"team1_pick" ""
	"team2_pick" ""
	}`

Would always team1 ban the first map, because the veto_mode overrules the veto_first value?
Because it would be nice if the first team would be random, if the 'veto_first random' mode is set :)

2023-04-07 23:36 UTC, nickdnk commented
The Cobblestone issue has been fixed in 0.14. See https://github.com/splewis/get5/releases/tag/v0.14.0 and remember to read the breaking changes. This is only a problem because Cobblestone is _misspelled_; it has nothing to do with it being a workshop map. It should work fine in 0.14.

> Just came up with another question.
> 
> What happens, if following values are set `"veto_first" "random" ` ` "veto_mode" { "team1_ban" "" "team2_ban" "" "team1_ban" "" "team2_ban" "" "team1_pick" "" "team2_pick" "" }`
> 
> Would always team1 ban the first map, because the veto_mode overrules the veto_first value? Because it would be nice if the first team would be random, if the 'veto_first random' mode is set :)

`veto_first` is ignored if you provide a custom veto mode. If you don't set a custom veto mode, `veto_first` just inverts the default veto mode listed here: https://splewis.github.io/get5/latest/veto/#default

2023-04-08 00:16 UTC, nickdnk commented
I've updated the documentation to clarify the questions you had about veto first.

2023-04-08 21:30 UTC, nickdnk commented
@deLuXe83 You may want to disable https://splewis.github.io/get5/latest/configuration/#get5_format_map_names - I added this to 0.14.1. If you have many workshop maps, it's preferable to not format any map names for consistency.

2023-04-10 08:58 UTC, deLuXe83 commented
allright i will check it out this week!
thank you very much 🙏🏻

2023-04-14 22:05 UTC, deLuXe83 commented
Hi!
Veto System is working fine.

But now we have the issue that - after voting workshop maps - we get the error
"invalid file id".
then when i change the map manually,
then our cvars in the config file (eg. mp_maxrounds) are not getting executed.

any ideas?
thx!!
![Unbenannt2](https://user-images.githubusercontent.com/37928770/232162617-83deb354-1a1a-4ba4-aa77-8cad1ec86dda.PNG)

2023-04-15 00:19 UTC, nickdnk commented
Please open an issue and fill out the issue template.